apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-user: bW9uZ28tdXNlcg==        # base64 for: mongo-user
  mongo-password: cGFzczEyMw==        # base64 for: pass123
